// 《元素决斗》关卡数据 — 20关
// 每关包含：固定牌库、敌人护甲序列、固定敌人行动序列、知识目标

export interface ArmorLayer {
  armorId: string;       // 护甲类型ID（对应ARMOR_TYPES）
  hp: number;            // 护甲耐久（通常1，特殊护甲可能更高）
  label?: string;        // 显示标签
}

export interface EnemyAction {
  type: 'attack' | 'shield' | 'strengthen' | 'corrode' | 'heal';
  value: number;
  label: string;         // 显示文字，如 "普通攻击 10伤"
  icon: string;          // emoji图标
}

// Boss独特特性配置
export interface BossTraits {
  // 破甲后限制出牌：只有这些牌才能攻击核心（其他牌造成反弹）
  // 用于引导学生在破甲后继续使用正确的化学牌
  postArmorBreakAllowed?: string[];  // 允许的卡牌ID列表
  postArmorBreakHint?: string;       // 破甲后的提示文字
  // 卡牌伤害倍率（相同牌对不同Boss效果不同）
  cardDamageMultipliers?: Record<string, number>; // cardId -> 倍率
  // Boss弱点（额外+50%伤害）
  weakToCards?: string[];
  // Boss免疫牌（出牌无效，不消耗次数）
  immuneToCards?: string[];
  // 特殊说明（化学原理）
  traitDescription?: string;

  // ── 章节Boss新机制 ──
  // 关5：钠爆机制 — Na护甲被水破除时触发水相钠爆，对玩家造成溅射伤害
  sodiumExplosion?: boolean;
  sodiumExplosionDamage?: number;
  sodiumExplosionHint?: string;

  // 关10：护甲再生机制 — 石灰石循环，Boss每3回合自动修复一层已破除的护甲
  armorRegen?: boolean;
  armorRegenInterval?: number;
  armorRegenMax?: number;
  armorRegenHint?: string;

  // 关15：活动性锁定机制 — Boss激活后，玩家只能用活动性更强的金属牌破甲
  activityLock?: boolean;
  activityLockInterval?: number;
  activityLockDuration?: number;
  activityOrder?: string[];
  activityLockHint?: string;

  // 关20：氧化还原护甲机制 — 护甲分氧化态和还原态，用错会给Boss回血
  redoxArmor?: boolean;
  initialRedoxState?: 'oxidized' | 'reduced';
  oxidizedBreakers?: string[];
  reducedBreakers?: string[];
  redoxWrongPenalty?: number;
  redoxHint?: string;
}

export interface Level {
  id: number;
  chapter: number;       // 章节 1-4
  title: string;
  subtitle: string;
  description: string;   // 关卡描述
  maxRounds: number;     // 最大回合数（超过则失败）
  enemyName: string;
  enemyEmoji: string;
  enemyHP: number;
  playerHP: number;
  // 敌人护甲序列：每N回合换一层（按顺序循环）
  armorSequence: ArmorLayer[];
  armorChangeInterval: number; // 每隔几回合换护甲（默认2）
  // 敌人固定行动序列（完全公开）
  enemyActions: EnemyAction[];
  // 玩家固定牌库（按顺序抽取，抽完后循环）
  playerDeck: string[];  // 卡牌ID列表
  // 初始手牌数量
  initialHandSize: number;
  // 每回合最多出牌/弃牌次数（默认2）
  maxPlaysPerTurn?: number;
  // Boss独特特性
  bossTraits?: BossTraits;
  // 关卡提示（隐藏模式：不直接高亮破甲牌，改为化学式提示）
  hint: string;
  // 通关后解锁的知识卡片
  knowledgeCardId: string;
  // 关卡目标描述
  objective: string;
  // 难度
  difficulty: 'easy' | 'medium' | 'hard';
  // 是否已解锁（初始只有第1关解锁）
  unlocked?: boolean;
}

export const LEVELS: Level[] = [
  // ═══════════════════════════════════
  // 第一章：元素初识（关卡1-5）
  // ═══════════════════════════════════
  {
    id: 1, chapter: 1,
    title: '氢与氧的相遇',
    subtitle: '第一章 · 元素初识',
    description: '最简单的两种元素，却能组成生命之水。学会出牌，击败水元素守卫！',
    maxRounds: 10, // 增加回合上限
    enemyName: '水元素守卫',
    enemyEmoji: '💧',
    enemyHP: 60, // 降低血量，加快节奏
    playerHP: 100,
    armorSequence: [
      { armorId: 'O2', hp: 1, label: '氧气护甲' },
      { armorId: 'O2', hp: 1, label: '氧气护甲' },
    ],
    armorChangeInterval: 4, // 减缓护甲切换
    enemyActions: [
      { type: 'attack', value: 6,  label: '水流冲击', icon: '💦' },
      { type: 'attack', value: 6,  label: '水流冲击', icon: '💦' },
      { type: 'shield', value: 10, label: '水膜防护', icon: '🛡️' },
      { type: 'attack', value: 10, label: '水压攻击', icon: '🌊' },
    ],
    // 优化牌库，确保环境牌和攻击牌成对出现
    playerDeck: ['Env_Ignite', 'H2', 'H2', 'O2', 'Env_Ignite', 'H2', 'H2', 'C', 'O2', 'H2'],
    initialHandSize: 4,
    maxPlaysPerTurn: 3, // 核心修复：每回合出牌次数增加到3次
    bossTraits: {
      weakToCards: ['H2'],
      cardDamageMultipliers: { 'H2': 1.5, 'C': 0.8 },
      traitDescription: '水元素守卫由氧气组成，对氢气（H₂）燃烧反应极其敏感！',
    },
    hint: '护甲化学式：O₂。第一步：打出【打火机】设置点燃环境；第二步：打出【H₂】产生燃烧反应！',
    knowledgeCardId: 'kc-H2',
    objective: '先用打火机点燃环境，再用氢气破除氧气护甲',
    difficulty: 'easy',
    unlocked: true,
  },
  {
    id: 2, chapter: 1,
    title: '钠的秘密',
    subtitle: '第一章 · 元素初识',
    description: '钠是一种神奇的金属——它遇水会剧烈反应！用水来破除钠护甲。',
    maxRounds: 8,
    enemyName: '钠晶守卫',
    enemyEmoji: '🧂',
    enemyHP: 90,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Na', hp: 1, label: '钠护甲' },
      { armorId: 'Na', hp: 1, label: '钠护甲' },
      { armorId: 'O2', hp: 1, label: '氧气护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack', value: 10, label: '钠光冲击', icon: '✨' },
      { type: 'attack', value: 10, label: '钠光冲击', icon: '✨' },
      { type: 'strengthen', value: 5, label: '碱化蓄力', icon: '⚡' },
      { type: 'attack', value: 15, label: '强碱腐蚀', icon: '🔥' },
      { type: 'attack', value: 10, label: '钠光冲击', icon: '✨' },
      { type: 'shield', value: 20, label: '氧化膜防护', icon: '🛡️' },
      { type: 'attack', value: 12, label: '钠光冲击', icon: '✨' },
      { type: 'attack', value: 18, label: '爆炸冲击', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Env_Ignite', 'H2', 'O2', 'H2O', 'C', 'H2O', 'Env_Aqueous', 'H2', 'O2', 'H2O', 'C'],
    initialHandSize: 3,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['H2O'],
      immuneToCards: ['C'],
      cardDamageMultipliers: { 'H2O': 1.6, 'H2': 0.7 },
      postArmorBreakAllowed: ['H2O', 'H2', 'O2'],
      postArmorBreakHint: '钠甲已破！核心暴露，但钠元素对碳完全免疫。用H₂O/H₂/O₂攻击！',
      traitDescription: '钠是活泼金属，遇水就会剧烈反应！但对碳元素完全免疫。2Na + 2H₂O → 2NaOH + H₂↑',
    },
    hint: '护甲化学式：Na。思考：活泼金属遇到什么会剧烈反应？（2Na + 2H₂O → 2NaOH + H₂↑）',
    knowledgeCardId: 'kc-Na',
    objective: '在8回合内击败钠晶守卫',
    difficulty: 'easy',
  },
  {
    id: 3, chapter: 1,
    title: '碱金属家族',
    subtitle: '第一章 · 元素初识',
    description: '锂、钠、钾——活泼性依次增强。钾比钠更危险！学会判断活泼性顺序。',
    maxRounds: 9,
    enemyName: '碱金属领主',
    enemyEmoji: '⚗️',
    enemyHP: 110,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Li', hp: 1, label: '锂护甲' },
      { armorId: 'Na', hp: 1, label: '钠护甲' },
      { armorId: 'K',  hp: 1, label: '钾护甲' },
    ],
    armorChangeInterval: 3,
    enemyActions: [
      { type: 'attack', value: 8,  label: '锂光射线', icon: '🔵' },
      { type: 'attack', value: 10, label: '钠光冲击', icon: '🟠' },
      { type: 'attack', value: 8,  label: '锂光射线', icon: '🔵' },
      { type: 'strengthen', value: 5, label: '活性蓄力', icon: '⚡' },
      { type: 'attack', value: 15, label: '钾爆冲击', icon: '🔴' },
      { type: 'attack', value: 10, label: '钠光冲击', icon: '🟠' },
      { type: 'shield', value: 25, label: '碱膜防护', icon: '🛡️' },
      { type: 'attack', value: 12, label: '钠光冲击', icon: '🟠' },
      { type: 'attack', value: 20, label: '钾爆大招', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'H2O', 'K', 'H2O', 'Li', 'Env_Aqueous', 'H2O', 'K', 'Na', 'H2O', 'K', 'H2O'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['H2O', 'K'],
      cardDamageMultipliers: { 'K': 1.8, 'H2O': 1.4, 'Na': 1.2, 'Li': 1.0 },
      traitDescription: '碑金属活泼性逐增：K > Na > Li。K牌对本关卒伤害最高！',
    },
    hint: '护甲化学式：Li、Na、K。思考：活泼性越强的金属与H₂O反应越剧烈，哪个牌伤害最高？',
    knowledgeCardId: 'kc-K',
    objective: '在9回合内击败碱金属领主',
    difficulty: 'easy',
  },
  {
    id: 4, chapter: 1,
    title: '卤素的腐蚀',
    subtitle: '第一章 · 元素初识',
    description: '卤素家族拥有强大的氧化性，能腐蚀金属。但稀有气体可以免疫腐蚀！',
    maxRounds: 9,
    enemyName: '氯气幽灵',
    enemyEmoji: '☁️',
    enemyHP: 100,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Cl', hp: 1, label: '氯护甲' },
      { armorId: 'Fe', hp: 1, label: '铁护甲' },
      { armorId: 'Cl', hp: 1, label: '氯护甲' },
    ],
    armorChangeInterval: 3,
    enemyActions: [
      { type: 'attack',   value: 10, label: '氯气腐蚀', icon: '☁️' },
      { type: 'corrode',  value: 8,  label: '氧化腐蚀（防御-8）', icon: '🧪' },
      { type: 'attack',   value: 12, label: '氯气腐蚀', icon: '☁️' },
      { type: 'attack',   value: 10, label: '氯气腐蚀', icon: '☁️' },
      { type: 'corrode',  value: 8,  label: '氧化腐蚀（防御-8）', icon: '🧪' },
      { type: 'strengthen',value: 8, label: '氧化蓄力', icon: '⚡' },
      { type: 'attack',   value: 18, label: '强氧化攻击', icon: '💥' },
      { type: 'attack',   value: 10, label: '氯气腐蚀', icon: '☁️' },
      { type: 'attack',   value: 15, label: '氯气腐蚀', icon: '☁️' },
    ],
    playerDeck: ['Env_Ignite', 'Fe', 'Ar', 'Na', 'Fe', 'Cl2', 'Env_Ignite', 'Ar', 'Fe', 'Na', 'Cl2', 'Ar', 'Fe'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['Fe', 'Na'],
      immuneToCards: ['H2', 'C'],
      cardDamageMultipliers: { 'Fe': 1.5, 'Na': 1.4, 'Cl2': 1.2 },
      traitDescription: '氯气幽灵由强氧化性氯气组成，对活泼金属（Fe、Na）极其敏感！对H₂和C完全免疫。2Fe + 3Cl₂ → 2FeCl₃',
    },
    hint: '护甲化学式：Cl、Fe。思考：氯气是强氧化剂，哪些金属能与它剧烈反应？氩气（Ar）能免疫腐蚀攻击。',
    knowledgeCardId: 'kc-Cl',
    objective: '在9回合内击败氯气幽灵',
    difficulty: 'easy',
  },
  {
    id: 5, chapter: 1,
    title: '食盐的诞生',
    subtitle: '第一章 · Boss关',
    description: '钠 + 氯 = 食盐（NaCl）！章节Boss，需要综合运用本章知识。',
    maxRounds: 10,
    enemyName: '食盐精灵 · NaCl',
    enemyEmoji: '🧂',
    enemyHP: 140,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Na', hp: 1, label: '钠护甲' },
      { armorId: 'Cl', hp: 1, label: '氯护甲' },
      { armorId: 'Na', hp: 1, label: '钠护甲' },
      { armorId: 'Cl', hp: 1, label: '氯护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '盐晶冲击', icon: '🧂' },
      { type: 'attack',    value: 12, label: '盐晶冲击', icon: '🧂' },
      { type: 'shield',    value: 20, label: '盐膜防护', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '钠光爆发', icon: '✨' },
      { type: 'corrode',   value: 10, label: '氯气腐蚀（防御-10）', icon: '☁️' },
      { type: 'attack',    value: 12, label: '盐晶冲击', icon: '🧂' },
      { type: 'strengthen',value: 10, label: '结晶蓄力', icon: '⚡' },
      { type: 'attack',    value: 20, label: '盐晶爆炸', icon: '💥' },
      { type: 'attack',    value: 12, label: '盐晶冲击', icon: '🧂' },
      { type: 'attack',    value: 25, label: '终极盐爆', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Fe', 'Ar', 'Env_Ignite', 'H2O', 'Cl2', 'K', 'H2O', 'Env_Aqueous', 'Fe', 'Ar', 'Cl2', 'K', 'H2O'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['H2O', 'Fe', 'K'],
      cardDamageMultipliers: { 'H2O': 1.5, 'Fe': 1.4, 'K': 1.6, 'Cl2': 1.3 },
      postArmorBreakAllowed: ['H2O', 'Fe', 'Ar', 'Cl2', 'K'],
      postArmorBreakHint: '护甲已破！食盐精灵由Na和Cl组成，需用化学反应牌（H₂O/Fe/Cl₂/K）才能攻击核心！',
      traitDescription: '食盐精灵由Na和Cl组成，护甲交替切换。K牌对本关卒伤害最高！Na + Cl₂ → NaCl',
      // 钠爆机制：用H₂O破Na护甲时，触发钓爆，对玩家造成溅射伤害
      // 化学原理：2Na + 2H₂O → 2NaOH + H₂↑ （放热剧烈，可能引发爆炸）
      sodiumExplosion: true,
      sodiumExplosionDamage: 10,
      sodiumExplosionHint: '钠爆！钓遇水剧烈反应：2Na + 2H₂O → 2NaOH + H₂↑，放热引发气体爆炸，溅射伤害 10点！但这是唯一能破Na护甲的方法——要学会承受代价！',
    },
    hint: '护甲化学式交替：Na、Cl。思考：哪些牌能破Na护甲？哪些牌能破Cl护甲？（提示：活泼金属遇水反应，金属点燃在氯气中燃烧）',
    knowledgeCardId: 'kc-NaCl',
    objective: '在10回合内击败食盐精灵',
    difficulty: 'medium',
  },

  // ═══════════════════════════════════
  // 第一章精英小怪（关卡21）
  // ═══════════════════════════════════
  {
    id: 21, chapter: 1,
    title: '元素精英挺身而出',
    subtitle: '第一章 · 精英挑战',
    description: '第一章的精英小怪出现了！它拥有更厉害的护甲和更快的攻击频率，考验你对第一章元素知识的掌握。',
    maxRounds: 10,
    enemyName: '元素精英守卫',
    enemyEmoji: '⚡',
    enemyHP: 160,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Na',  hp: 1, label: '钠护甲' },
      { armorId: 'O2',  hp: 1, label: '氧气护甲' },
      { armorId: 'Cl',  hp: 1, label: '氯护甲' },
      { armorId: 'Na',  hp: 1, label: '钠护甲' },
      { armorId: 'O2',  hp: 1, label: '氧气护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 14, label: '精英冲击', icon: '⚡' },
      { type: 'corrode',   value: 10, label: '元素腐蚀（防御-10）', icon: '🧪' },
      { type: 'attack',    value: 14, label: '精英冲击', icon: '⚡' },
      { type: 'strengthen',value: 10, label: '精英蓄力', icon: '⚡' },
      { type: 'attack',    value: 24, label: '精英爆发', icon: '💥' },
      { type: 'attack',    value: 14, label: '精英冲击', icon: '⚡' },
      { type: 'shield',    value: 25, label: '元素护盾', icon: '🛡️' },
      { type: 'attack',    value: 14, label: '精英冲击', icon: '⚡' },
      { type: 'corrode',   value: 12, label: '强元素腐蚀（防御-12）', icon: '🧪' },
      { type: 'attack',    value: 30, label: '终极精英爆发', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Env_Ignite', 'H2', 'Fe', 'H2O', 'Cl2', 'K', 'H2O', 'Env_Aqueous', 'Fe', 'Ar', 'Cl2', 'K', 'H2O'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['H2O', 'H2', 'Fe'],
      cardDamageMultipliers: { 'H2O': 1.5, 'H2': 1.4, 'Fe': 1.4, 'K': 1.6, 'Cl2': 1.3 },
      traitDescription: '元素精英守卫综合了第一章所有元素的力量！需要继合运用Na、O₂、Cl的化学知识才能获胜。',
      sodiumExplosion: true,
      sodiumExplosionDamage: 8,
      sodiumExplosionHint: '钠爆！钠遇水剧烈反应：2Na + 2H₂O → 2NaOH + H₂↑，溅射伤害 8点！',
    },
    hint: '护甲序列：Na、O₂、Cl交替切换。综合运用第一章所学的全部知识！',
    knowledgeCardId: 'kc-NaCl',
    objective: '在10回合内击败元素精英守卫',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第二章：化学反应（关卡-）
  // ═══════════════════════════════════
  {
    id: 6, chapter: 2,
    title: '酸碱中和',
    subtitle: '第二章 · 化学反应',
    description: '酸 + 碱 → 盐 + 水。酸碱双面怪的护甲会交替切换，你必须随机应变！',
    maxRounds: 10,
    enemyName: '酸碱双面怪',
    enemyEmoji: '⚗️',
    enemyHP: 120,
    playerHP: 100,
    armorSequence: [
      { armorId: 'HCl',  hp: 1, label: '酸护甲（HCl）' },
      { armorId: 'NaOH', hp: 1, label: '碱护甲（NaOH）' },
      { armorId: 'HCl',  hp: 1, label: '酸护甲（HCl）' },
      { armorId: 'NaOH', hp: 1, label: '碱护甲（NaOH）' },
      { armorId: 'HCl',  hp: 1, label: '酸护甲（HCl）' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 10, label: '酸液喷射', icon: '🧪' },
      { type: 'attack',    value: 10, label: '碱液冲击', icon: '🔵' },
      { type: 'strengthen',value: 8,  label: 'pH蓄力', icon: '⚡' },
      { type: 'attack',    value: 18, label: '强酸腐蚀', icon: '💥' },
      { type: 'attack',    value: 10, label: '酸液喷射', icon: '🧪' },
      { type: 'corrode',   value: 10, label: '酸碱腐蚀（防御-10）', icon: '🧪' },
      { type: 'attack',    value: 12, label: '碱液冲击', icon: '🔵' },
      { type: 'strengthen',value: 8,  label: 'pH蓄力', icon: '⚡' },
      { type: 'attack',    value: 20, label: '中和爆炸', icon: '💥' },
      { type: 'attack',    value: 15, label: '终极腐蚀', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'NaOH', 'HCl', 'NaOH', 'Ca_OH_2', 'HCl', 'Env_Aqueous', 'NaOH', 'Ar', 'HCl', 'NaOH', 'Ca_OH_2', 'HCl', 'Ar'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['NaOH', 'HCl'],
      cardDamageMultipliers: { 'NaOH': 1.4, 'HCl': 1.4, 'Ca_OH_2': 1.3 },
      postArmorBreakAllowed: ['NaOH', 'HCl', 'Ca_OH_2', 'Ar'],
      postArmorBreakHint: '护甲已破！酸碱双面怪对非酸碱牌免疫。用NaOH/HCl/Ca(OH)₂攻击！',
      traitDescription: '酸碱双面怪由酸和碱交替护甲。酸碱中和反应：NaOH + HCl → NaCl + H₂O',
    },
    hint: '护甲化学式交替：HCl、NaOH。思考：酸和碱发生什么反应？哪些牌能破酸护甲？哪些牌能破碱护甲？',
    knowledgeCardId: 'kc-NaOH',
    objective: '在10回合内击败酸碱双面怪',
    difficulty: 'medium',
  },
  {
    id: 7, chapter: 2,
    title: '碳的燃烧',
    subtitle: '第二章 · 化学反应',
    description: '碳在氧气中燃烧生成CO₂，CO₂又能与碱反应。掌握碳的化学循环！',
    maxRounds: 10,
    enemyName: '碳烟魔王',
    enemyEmoji: '🔥',
    enemyHP: 130,
    playerHP: 100,
    armorSequence: [
      { armorId: 'O2',   hp: 1, label: '氧气护甲' },
      { armorId: 'CO2',  hp: 1, label: 'CO₂护甲' },
      { armorId: 'O2',   hp: 1, label: '氧气护甲' },
      { armorId: 'CO2',  hp: 1, label: 'CO₂护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '烟雾攻击', icon: '💨' },
      { type: 'attack',    value: 12, label: '烟雾攻击', icon: '💨' },
      { type: 'strengthen',value: 8,  label: '燃烧蓄力', icon: '🔥' },
      { type: 'attack',    value: 20, label: '火焰冲击', icon: '🔥' },
      { type: 'attack',    value: 12, label: '烟雾攻击', icon: '💨' },
      { type: 'shield',    value: 25, label: '碳膜防护', icon: '🛡️' },
      { type: 'attack',    value: 12, label: '烟雾攻击', icon: '💨' },
      { type: 'strengthen',value: 10, label: '燃烧蓄力', icon: '🔥' },
      { type: 'attack',    value: 22, label: '碳爆冲击', icon: '💥' },
      { type: 'attack',    value: 18, label: '终极烟雾', icon: '💥' },
    ],
    playerDeck: ['Env_Heat', 'C', 'Ca_OH_2', 'Env_Ignite', 'H2', 'C', 'NaOH', 'Env_Aqueous', 'Ca_OH_2', 'C', 'H2', 'NaOH', 'C', 'Ca_OH_2', 'H2'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['C', 'Ca_OH_2'],
      immuneToCards: ['HCl', 'NaOH'],
      cardDamageMultipliers: { 'C': 1.6, 'Ca_OH_2': 1.5, 'H2': 1.3, 'NaOH': 1.2 },
      traitDescription: '碳烟魔王由碳元素组成，对碳的燃烧反应极其敏感！C + O₂ → CO₂，CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',
    },
    hint: '护甲化学式交替：O₂、CO₂。思考：碳燃烧产生什么？CO₂又能与什么反应？（提示：石灰水变浑是检验CO₂的经典实验）',
    knowledgeCardId: 'kc-C',
    objective: '在10回合内击败碳烟魔王',
    difficulty: 'medium',
  },
  {
    id: 8, chapter: 2,
    title: '铁的锈蚀',
    subtitle: '第二章 · 化学反应',
    description: '铁生锈（Fe₂O₃）是氧化反应，铁锈可以被酸溶解，也可以被碳还原。',
    maxRounds: 10,
    enemyName: '铁锈巨人',
    enemyEmoji: '🦾',
    enemyHP: 140,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'Fe',    hp: 1, label: '铁护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'Fe',    hp: 1, label: '铁护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '铁拳重击', icon: '👊' },
      { type: 'attack',    value: 12, label: '铁拳重击', icon: '👊' },
      { type: 'shield',    value: 20, label: '铁甲防护', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '铁锈冲击', icon: '🦾' },
      { type: 'attack',    value: 12, label: '铁拳重击', icon: '👊' },
      { type: 'strengthen',value: 10, label: '锈化蓄力', icon: '⚡' },
      { type: 'attack',    value: 20, label: '重锤砸击', icon: '💥' },
      { type: 'attack',    value: 12, label: '铁拳重击', icon: '👊' },
      { type: 'shield',    value: 25, label: '铁甲防护', icon: '🛡️' },
      { type: 'attack',    value: 25, label: '终极铁拳', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'HCl', 'Env_Heat', 'C', 'Env_Ignite', 'H2', 'HCl', 'Cl2', 'C', 'Env_Aqueous', 'HCl', 'H2', 'Cl2', 'HCl', 'C', 'H2'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['HCl', 'C'],
      cardDamageMultipliers: { 'HCl': 1.5, 'C': 1.4, 'H2': 1.3, 'Cl2': 1.2 },
      postArmorBreakAllowed: ['HCl', 'C', 'H2', 'Cl2'],
      postArmorBreakHint: '护甲已破！铁锈巨人对非化学反应牌免疫。用HCl/C/H₂/Cl₂攻击！',
      traitDescription: '铁锈巨人由Fe和Fe₂O₃组成。HCl对本关卒伤害最高！Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O',
    },
    hint: '护甲化学式交替：Fe₂O₃、Fe。思考：酸能溶解金属氧化物吗？还原剂能还原铁锈吗？（提示：高炉炼铁用焦炭还原铁锈）',
    knowledgeCardId: 'kc-Fe',
    objective: '在10回合内击败铁锈巨人',
    difficulty: 'medium',
  },
  {
    id: 9, chapter: 2,
    title: '催化剂的魔法',
    subtitle: '第二章 · 化学反应',
    description: '催化剂MnO₂可以加快反应速率！学会用MnO₂在同一回合连续出两张牌。',
    maxRounds: 10,
    enemyName: '反应速率魔法师',
    enemyEmoji: '🧙',
    enemyHP: 150,
    playerHP: 100,
    armorSequence: [
      { armorId: 'O2',    hp: 1, label: '氧气护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（高温还原）' },
      { armorId: 'O2',    hp: 1, label: '氧气护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '魔法冲击', icon: '✨' },
      { type: 'strengthen',value: 8,  label: '加速蓄力', icon: '⚡' },
      { type: 'attack',    value: 20, label: '加速攻击', icon: '💨' },
      { type: 'shield',    value: 30, label: '魔法护盾', icon: '🛡️' },
      { type: 'attack',    value: 12, label: '魔法冲击', icon: '✨' },
      { type: 'attack',    value: 12, label: '魔法冲击', icon: '✨' },
      { type: 'strengthen',value: 10, label: '超速蓄力', icon: '⚡' },
      { type: 'attack',    value: 22, label: '超速攻击', icon: '💥' },
      { type: 'attack',    value: 12, label: '魔法冲击', icon: '✨' },
      { type: 'attack',    value: 28, label: '终极魔法', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'MnO2', 'Env_Ignite', 'H2', 'HCl', 'MnO2', 'Env_Aqueous', 'Fe', 'NaOH', 'MnO2', 'Env_Heat', 'C', 'Cl2', 'H2', 'HCl', 'MnO2'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['MnO2'],
      cardDamageMultipliers: { 'MnO2': 1.0, 'H2': 1.4, 'HCl': 1.3, 'Fe': 1.3, 'C': 1.2, 'Cl2': 1.2 },
      traitDescription: '反应速率魔法师对催化剂有特殊感应！MnO₂不消耗出牌次数，可以连续出牌。催化剂加快反应速率但不改变反应结果。',
    },
    hint: '护甲化学式：O₂、NaOH、Fe₂O₃、Fe₂O₃、O₂。思考：催化剑能加快反应，如何利用它在同一回合连续出牌？高温还原需要C或H₂。',
    knowledgeCardId: 'kc-MnO2',
    objective: '在10回合内击败反应速率魔法师',
    difficulty: 'medium',
  },
  {
    id: 10, chapter: 2,
    title: '石灰石的秘密',
    subtitle: '第二章 · Boss关',
    description: '石灰石（CaCO₃）遇酸分解，高温分解生成CaO，CaO遇水生成Ca(OH)₂。碳酸钙循环！',
    maxRounds: 12,
    enemyName: '石灰石巨龙',
    enemyEmoji: '🐉',
    enemyHP: 180,
    playerHP: 100,
    armorSequence: [
      { armorId: 'CaCO3', hp: 1, label: '石灰石护甲' },
      { armorId: 'CO2',   hp: 1, label: 'CO₂护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'CaCO3', hp: 1, label: '石灰石护甲' },
      { armorId: 'CO2',   hp: 1, label: 'CO₂护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 14, label: '石块投掷', icon: '🪨' },
      { type: 'attack',    value: 14, label: '石块投掷', icon: '🪨' },
      { type: 'shield',    value: 25, label: '石灰防护', icon: '🛡️' },
      { type: 'attack',    value: 20, label: '龙息冲击', icon: '🔥' },
      { type: 'attack',    value: 14, label: '石块投掷', icon: '🪨' },
      { type: 'strengthen',value: 12, label: '龙力蓄力', icon: '⚡' },
      { type: 'attack',    value: 25, label: '巨龙冲撞', icon: '💥' },
      { type: 'attack',    value: 14, label: '石块投掷', icon: '🪨' },
      { type: 'shield',    value: 30, label: '石灰防护', icon: '🛡️' },
      { type: 'attack',    value: 14, label: '石块投掷', icon: '🪨' },
      { type: 'strengthen',value: 15, label: '终极蓄力', icon: '⚡' },
      { type: 'attack',    value: 35, label: '终极龙息', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'HCl', 'Ca_OH_2', 'Env_Heat', 'C', 'HCl', 'NaOH', 'Env_Aqueous', 'Ca_OH_2', 'HCl', 'C', 'NaOH', 'Ca_OH_2', 'HCl', 'C', 'NaOH'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['HCl', 'Ca_OH_2'],
      cardDamageMultipliers: { 'HCl': 1.6, 'Ca_OH_2': 1.5, 'C': 1.3, 'NaOH': 1.2 },
      postArmorBreakAllowed: ['HCl', 'Ca_OH_2', 'C', 'NaOH'],
      postArmorBreakHint: '护甲已破！石灰石巨龙对非化学反应牌免疫。用HCl/Ca(OH)₂/C/NaOH攻击！',
      traitDescription: '石灰石巨龙由CaCO₃循环组成。HCl对本关卒伤害最高！CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑',
      // 护甲再生机制：石灰石循环——每3回合再生一层已破除的护甲
      // 化学原理：CaO + H₂O → Ca(OH)₂，Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O（石灰石循环）
      armorRegen: true,
      armorRegenInterval: 3,
      armorRegenMax: 2,
      armorRegenHint: '石灰石循环再生！CaO + H₂O → Ca(OH)₂，Ca(OH)₂ + CO₂ → CaCO₃↓——石灰石巨龙利用化学循环修复了一层护甲！必须加快攻击节奏！',
    },
    hint: '护甲化学式循环：CaCO₃、CO₂、NaOH。思考：酸能溶解石灰石吗？CO₂能被什么吸收？（提示：石灰石遗址就是用酸雕刻的）',
    knowledgeCardId: 'kc-CaCO3',
    objective: '在12回合内击败石灰石巨龙',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第二章精英小怪（关卡22）
  // ═══════════════════════════════════
  {
    id: 22, chapter: 2,
    title: '反应精英降临',
    subtitle: '第二章 · 精英挑战',
    description: '化学反应精英出现！它综合了酸碱中和、碳的燃烧、鐵的锈蚀和山灰石循环的力量，需要综合运用第二章知识才能获胜！',
    maxRounds: 12,
    enemyName: '化学反应精英',
    enemyEmoji: '⚯️',
    enemyHP: 190,
    playerHP: 100,
    armorSequence: [
      { armorId: 'HCl',   hp: 1, label: '酸护甲（HCl）' },
      { armorId: 'Fe2O3', hp: 1, label: '鐵锈护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲（NaOH）' },
      { armorId: 'CO2',   hp: 1, label: 'CO₂护甲' },
      { armorId: 'HCl',   hp: 1, label: '酸护甲（HCl）' },
      { armorId: 'Fe2O3', hp: 1, label: '鐵锈护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 15, label: '反应冲击', icon: '⚯️' },
      { type: 'corrode',   value: 12, label: '酸碱腐蚀（防御-12）', icon: '🧪' },
      { type: 'attack',    value: 15, label: '反应冲击', icon: '⚯️' },
      { type: 'strengthen',value: 12, label: '反应蓄力', icon: '⚡' },
      { type: 'attack',    value: 27, label: '反应爆发', icon: '💥' },
      { type: 'shield',    value: 30, label: '反应护盾', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '反应冲击', icon: '⚯️' },
      { type: 'corrode',   value: 15, label: '强化学腐蚀（防御-15）', icon: '🧪' },
      { type: 'strengthen',value: 15, label: '超级反应蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '反应大爆发', icon: '💥' },
      { type: 'attack',    value: 15, label: '反应冲击', icon: '⚯️' },
      { type: 'attack',    value: 35, label: '终极化学反应', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'NaOH', 'HCl', 'Env_Heat', 'C', 'Ca_OH_2', 'MnO2', 'HCl', 'Env_Aqueous', 'NaOH', 'C', 'Ca_OH_2', 'MnO2', 'HCl', 'NaOH', 'C'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['NaOH', 'HCl', 'C'],
      cardDamageMultipliers: { 'NaOH': 1.5, 'HCl': 1.5, 'C': 1.4, 'Ca_OH_2': 1.3, 'MnO2': 1.0 },
      traitDescription: '化学反应精英综合了第二章所有反应类型！酸碱中和、碳的燃烧、鐵的还原和山灰石循环。MnO₂不消耗出牌次数，合理利用将事半功倍！',
      armorRegen: true,
      armorRegenInterval: 4,
      armorRegenMax: 1,
      armorRegenHint: '化学循环再生！化学反应精英利用石灰石循环修复了一层护甲！加快攻击节奏！',
    },
    hint: '护甲序列：HCl、Fe₂O₃、NaOH、CO₂交替。综合运用第二章全部化学知识！小心护甲再生机制！',
    knowledgeCardId: 'kc-CaCO3',
    objective: '在12回合内击败化学反应精英',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第三章：金属活动性（关卡11-15）
  // ═══════════════════════════════════
  {
    id: 11, chapter: 3,
    title: '金属活动性顺序',
    subtitle: '第三章 · 金属世界',
    description: '金属活动性顺序：K>Na>Ca>Mg>Al>Zn>Fe>Ni>Sn>Pb>H>Cu>Hg>Ag>Pt>Au。活泼金属能置换不活泼金属！',
    maxRounds: 10,
    enemyName: '铜甲武士',
    enemyEmoji: '🗡️',
    enemyHP: 130,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Cu',  hp: 1, label: '铜护甲' },
      { armorId: 'Fe',  hp: 1, label: '铁护甲' },
      { armorId: 'Cu',  hp: 1, label: '铜护甲' },
      { armorId: 'Al',  hp: 1, label: '铝护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '铜剑劈砍', icon: '⚔️' },
      { type: 'attack',    value: 12, label: '铜剑劈砍', icon: '⚔️' },
      { type: 'shield',    value: 20, label: '铜盾防御', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '铁拳重击', icon: '👊' },
      { type: 'attack',    value: 12, label: '铜剑劈砍', icon: '⚔️' },
      { type: 'strengthen',value: 10, label: '金属蓄力', icon: '⚡' },
      { type: 'attack',    value: 22, label: '合金冲击', icon: '💥' },
      { type: 'attack',    value: 12, label: '铜剑劈砍', icon: '⚔️' },
      { type: 'shield',    value: 25, label: '铝盾防御', icon: '🛡️' },
      { type: 'attack',    value: 25, label: '终极金属冲击', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'Fe', 'Zn', 'HCl', 'Fe', 'NaOH', 'Env_Aqueous', 'Zn', 'Fe', 'HCl', 'NaOH', 'Zn', 'Fe', 'HCl'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['Fe', 'Zn'],
      cardDamageMultipliers: { 'Fe': 1.5, 'Zn': 1.4, 'HCl': 1.3, 'NaOH': 1.3 },
      postArmorBreakAllowed: ['Fe', 'Zn', 'HCl', 'NaOH'],
      postArmorBreakHint: '护甲已破！铜甲武士对非置换/酸碱牌免疫。用Fe/Zn/HCl/NaOH攻击！',
      traitDescription: '铜甲武士由Cu、Fe、Al护甲组成。Fe置换Cu伤害最高！Fe + CuSO₄ → FeSO₄ + Cu',
    },
    hint: '护甲化学式序列：Cu、Fe、Cu、Al。思考：金属活动性顺序如何决定置换反应？哪些金属能置换Cu？哪些能置换Fe？',
    knowledgeCardId: 'kc-activity',
    objective: '在10回合内击败铜甲武士',
    difficulty: 'medium',
  },
  {
    id: 12, chapter: 3,
    title: '铝的两性',
    subtitle: '第三章 · 金属世界',
    description: '铝是两性金属——既能与酸反应，也能与碱反应！这让它的护甲有独特弱点。',
    maxRounds: 10,
    enemyName: '铝合金卫士',
    enemyEmoji: '🤖',
    enemyHP: 140,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Al',   hp: 1, label: '铝护甲（酸碱均可破）' },
      { armorId: 'Al',   hp: 1, label: '铝护甲（酸碱均可破）' },
      { armorId: 'Fe',   hp: 1, label: '铁护甲' },
      { armorId: 'Al',   hp: 1, label: '铝护甲（酸碱均可破）' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 12, label: '铝拳冲击', icon: '🤖' },
      { type: 'attack',    value: 12, label: '铝拳冲击', icon: '🤖' },
      { type: 'strengthen',value: 10, label: '合金蓄力', icon: '⚡' },
      { type: 'attack',    value: 22, label: '合金重击', icon: '💥' },
      { type: 'attack',    value: 12, label: '铝拳冲击', icon: '🤖' },
      { type: 'shield',    value: 25, label: '氧化铝防护', icon: '🛡️' },
      { type: 'attack',    value: 12, label: '铝拳冲击', icon: '🤖' },
      { type: 'strengthen',value: 12, label: '超级蓄力', icon: '⚡' },
      { type: 'attack',    value: 25, label: '超级合金冲击', icon: '💥' },
      { type: 'attack',    value: 18, label: '终极铝拳', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'HCl', 'NaOH', 'HCl', 'Zn', 'NaOH', 'HCl', 'Env_Aqueous', 'Litmus', 'NaOH', 'HCl', 'Zn', 'NaOH', 'HCl'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['HCl', 'NaOH'],
      cardDamageMultipliers: { 'HCl': 1.5, 'NaOH': 1.5, 'Zn': 1.3 },
      traitDescription: '铝合金卫士由铝护甲组成。铝是两性金属，酸碱均可破！HCl/NaOH对本关卒伤害最高、2Al + 6HCl → 2AlCl₃ + 3H₂↑',
    },
    hint: '护甲化学式：Al、Al、Fe、Al。思考：铝是两性金属，酸和碱都能与它反应。石蕊试液能帮你判断护甲类型吗？',
    knowledgeCardId: 'kc-Al',
    objective: '在10回合内击败铝合金卫士',
    difficulty: 'medium',
  },
  {
    id: 13, chapter: 3,
    title: '硫酸的威力',
    subtitle: '第三章 · 金属世界',
    description: '硫酸（H₂SO₄）是工业上最重要的酸，能与多种金属和碱反应。但铁在浓硫酸中会钝化！',
    maxRounds: 11,
    enemyName: '硫酸海怪',
    enemyEmoji: '🐙',
    enemyHP: 160,
    playerHP: 100,
    armorSequence: [
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'Al',    hp: 1, label: '铝护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'Al',    hp: 1, label: '铝护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 14, label: '酸液喷射', icon: '🧪' },
      { type: 'corrode',   value: 10, label: '硫酸腐蚀（防御-10）', icon: '💧' },
      { type: 'attack',    value: 14, label: '酸液喷射', icon: '🧪' },
      { type: 'strengthen',value: 10, label: '酸化蓄力', icon: '⚡' },
      { type: 'attack',    value: 24, label: '强酸冲击', icon: '💥' },
      { type: 'attack',    value: 14, label: '酸液喷射', icon: '🧪' },
      { type: 'corrode',   value: 12, label: '硫酸腐蚀（防御-12）', icon: '💧' },
      { type: 'shield',    value: 30, label: '酸膜防护', icon: '🛡️' },
      { type: 'attack',    value: 14, label: '酸液喷射', icon: '🧪' },
      { type: 'strengthen',value: 15, label: '超酸蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '硫酸大爆发', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2SO4', 'NaOH', 'H2SO4', 'Ar', 'Ca_OH_2', 'Env_Aqueous', 'H2SO4', 'NaOH', 'Ar', 'H2SO4', 'Ca_OH_2', 'NaOH', 'H2SO4'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['H2SO4'],
      immuneToCards: ['H2', 'C'],
      cardDamageMultipliers: { 'H2SO4': 1.6, 'NaOH': 1.4, 'Ca_OH_2': 1.3 },
      postArmorBreakAllowed: ['H2SO4', 'NaOH', 'Ca_OH_2', 'Ar'],
      postArmorBreakHint: '护甲已破！硫酸海怪对H₂和C完全免疫。用H₂SO₄/NaOH/Ca(OH)₂攻击！',
      traitDescription: '硫酸海怪由H₂SO₄组成。H₂SO₄对本关卒伤害最高！H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O',
    },
    hint: '护甲化学式序列：NaOH、Al、Fe₂O₃、NaOH、Al。思考：稀硫酸能与哪些物质反应？注意：实验室制CO₂用HCl而非H₂SO₄，因为CaSO₄微溶会阻止反应继续！',
    knowledgeCardId: 'kc-H2SO4',
    objective: '在11回合内击败硫酸海怪',
    difficulty: 'hard',
  },
  {
    id: 14, chapter: 3,
    title: '置换反应链',
    subtitle: '第三章 · 金属世界',
    description: '活动性顺序决定置换反应！Zn>Fe>Cu，用正确的金属牌置换对应的护甲。',
    maxRounds: 11,
    enemyName: '金属链守护者',
    enemyEmoji: '⛓️',
    enemyHP: 170,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Cu',  hp: 1, label: '铜护甲' },
      { armorId: 'Fe',  hp: 1, label: '铁护甲' },
      { armorId: 'Al',  hp: 1, label: '铝护甲' },
      { armorId: 'Cu',  hp: 1, label: '铜护甲' },
      { armorId: 'Fe',  hp: 1, label: '铁护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 14, label: '链条抽打', icon: '⛓️' },
      { type: 'attack',    value: 14, label: '链条抽打', icon: '⛓️' },
      { type: 'shield',    value: 25, label: '金属链防护', icon: '🛡️' },
      { type: 'attack',    value: 20, label: '链条重击', icon: '💥' },
      { type: 'attack',    value: 14, label: '链条抽打', icon: '⛓️' },
      { type: 'strengthen',value: 12, label: '链力蓄力', icon: '⚡' },
      { type: 'attack',    value: 26, label: '链条狂击', icon: '💥' },
      { type: 'attack',    value: 14, label: '链条抽打', icon: '⛓️' },
      { type: 'shield',    value: 30, label: '金属链防护', icon: '🛡️' },
      { type: 'attack',    value: 14, label: '链条抽打', icon: '⛓️' },
      { type: 'attack',    value: 30, label: '终极链击', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'Fe', 'Zn', 'HCl', 'NaOH', 'Fe', 'Env_Aqueous', 'Zn', 'HCl', 'NaOH', 'Fe', 'Zn', 'HCl', 'NaOH'],
    initialHandSize: 4,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['Fe', 'Zn', 'NaOH'],
      cardDamageMultipliers: { 'Fe': 1.5, 'Zn': 1.5, 'NaOH': 1.4, 'HCl': 1.3 },
      traitDescription: '金属链守护者由Cu、Fe、Al护甲序列组成。Fe置换Cu，Zn置换Fe，NaOH破Al！这是置换反应的典范链。',
    },
    hint: '护甲化学式序列：Cu、Fe、Al、Cu、Fe。思考：活动性顺序如何决定置换反应？提前规划每张牌的用途。',
    knowledgeCardId: 'kc-displacement',
    objective: '在11回合内击败金属链守护者',
    difficulty: 'hard',
  },
  {
    id: 15, chapter: 3,
    title: '金属世界Boss',
    subtitle: '第三章 · Boss关',
    description: '金属炼金师掌握所有金属的秘密！综合运用置换反应、酸碱反应和催化技能。',
    maxRounds: 12,
    enemyName: '金属炼金师',
    enemyEmoji: '⚗️',
    enemyHP: 200,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Al',    hp: 1, label: '铝护甲（酸碱均可）' },
      { armorId: 'Fe',    hp: 1, label: '铁护甲' },
      { armorId: 'Cu',    hp: 1, label: '铜护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'CaCO3', hp: 1, label: '石灰石护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 15, label: '炼金冲击', icon: '⚗️' },
      { type: 'corrode',   value: 10, label: '腐蚀（防御-10）', icon: '🧪' },
      { type: 'attack',    value: 15, label: '炼金冲击', icon: '⚗️' },
      { type: 'strengthen',value: 12, label: '炼金蓄力', icon: '⚡' },
      { type: 'attack',    value: 27, label: '炼金爆发', icon: '💥' },
      { type: 'shield',    value: 30, label: '金属护盾', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '炼金冲击', icon: '⚗️' },
      { type: 'corrode',   value: 12, label: '腐蚀（防御-12）', icon: '🧪' },
      { type: 'strengthen',value: 15, label: '超级蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '超级炼金爆发', icon: '💥' },
      { type: 'attack',    value: 15, label: '炼金冲击', icon: '⚗️' },
      { type: 'attack',    value: 35, label: '终极炼金术', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'HCl', 'Zn', 'Fe', 'NaOH', 'MnO2', 'HCl', 'Env_Aqueous', 'Ar', 'H2SO4', 'Ca_OH_2', 'HCl', 'Zn', 'MnO2', 'NaOH'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['HCl', 'H2SO4', 'Fe', 'Zn'],
      cardDamageMultipliers: { 'HCl': 1.4, 'H2SO4': 1.5, 'Fe': 1.4, 'Zn': 1.4, 'NaOH': 1.3, 'MnO2': 1.0 },
      postArmorBreakAllowed: ['HCl', 'Zn', 'Fe', 'NaOH', 'H2SO4', 'Ca_OH_2', 'Ar', 'MnO2'],
      postArmorBreakHint: '护甲已破！金属炼金师对非化学反应牌免疫。用化学反应牌攻击！',
      traitDescription: '金属炼金师掉有所有金属的秘密！H₂SO₄对本关卒伤害最高。综合运用置换反应、酸碱反应和催化剂。',
      // 活动性锁定机制：每3回合激活，持续2回合
      // 化学原理：置换反应条件——活动性强的金属才能置换活动性弱的金属（K>Ca>Na>Mg>Al>Zn>Fe>Cu>Ag）
      activityLock: true,
      activityLockInterval: 3,
      activityLockDuration: 2,
      activityOrder: ['K', 'Na', 'Ca', 'Mg', 'Al', 'Zn', 'Fe', 'Cu', 'Ag'],
      activityLockHint: '活动性锁定激活！金属炼金师击活了活动性屏障：置换反应需要活动性更强的金属！现在只有活动性强于当前护甲金属的牌才能破甲，否则反弹！',
    },
    hint: '护甲化学式序列：Al、Fe、Cu、Fe₂O₃、NaOH、CaCO₃。思考：如何合理分配手牌中的酸、碱、金属牌？催化剂能帮你连续出牌。',
    knowledgeCardId: 'kc-metals',
    objective: '在12回合内击败金属炼金师',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第三章精英小怪（关卡23）
  // ═══════════════════════════════════
  {
    id: 23, chapter: 3,
    title: '金属精英现身',
    subtitle: '第三章 · 精英挑战',
    description: '金属精英出现！它综合了金属活动性、置换反应和硫酸的力量，并拥有活动性锁定机制！需要综合运用第三章知识才能获胜。',
    maxRounds: 12,
    enemyName: '金属精英战士',
    enemyEmoji: '⚔️',
    enemyHP: 210,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Cu',    hp: 1, label: '铜护甲' },
      { armorId: 'Al',    hp: 1, label: '铝护甲（酸碱均可破）' },
      { armorId: 'Fe',    hp: 1, label: '铁护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'Cu',    hp: 1, label: '铜护甲' },
      { armorId: 'Al',    hp: 1, label: '铝护甲（酸碱均可破）' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 15, label: '金属冲击', icon: '⚔️' },
      { type: 'corrode',   value: 12, label: '硫酸腐蚀（防御-12）', icon: '🧪' },
      { type: 'attack',    value: 15, label: '金属冲击', icon: '⚔️' },
      { type: 'strengthen',value: 12, label: '金属蓄力', icon: '⚡' },
      { type: 'attack',    value: 27, label: '金属爆发', icon: '💥' },
      { type: 'shield',    value: 30, label: '金属护盾', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '金属冲击', icon: '⚔️' },
      { type: 'corrode',   value: 15, label: '强硫酸腐蚀（防御-15）', icon: '🧪' },
      { type: 'strengthen',value: 15, label: '超级金属蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '金属大爆发', icon: '💥' },
      { type: 'attack',    value: 15, label: '金属冲击', icon: '⚔️' },
      { type: 'attack',    value: 35, label: '终极金属冲击', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'Fe', 'Zn', 'HCl', 'NaOH', 'H2SO4', 'Fe', 'Env_Aqueous', 'Zn', 'HCl', 'NaOH', 'H2SO4', 'Fe', 'Zn', 'HCl'],
    initialHandSize: 5,
    maxPlaysPerTurn: 2,
    bossTraits: {
      weakToCards: ['Fe', 'Zn', 'HCl'],
      cardDamageMultipliers: { 'Fe': 1.5, 'Zn': 1.5, 'HCl': 1.4, 'NaOH': 1.4, 'H2SO4': 1.5 },
      traitDescription: '金属精英战士综合了第三章所有金属知识！Cu用Fe置换，Al用HCl/NaOH破，Fe用Zn置换，Fe₂O₃用HCl或C还原。',
      activityLock: true,
      activityLockInterval: 3,
      activityLockDuration: 2,
      activityOrder: ['K', 'Na', 'Ca', 'Mg', 'Al', 'Zn', 'Fe', 'Cu', 'Ag'],
      activityLockHint: '活动性锁定激活！置换反应需要活动性更强的金属！错误将造成反弹！',
    },
    hint: '护甲序列：Cu、Al、Fe、Fe₂O₃交替。小心活动性锁定机制！综合运用第三章全部金属知识！',
    knowledgeCardId: 'kc-metals',
    objective: '在12回合内击败金属精英战士',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第四章：综合挑战（关卡16-20）
  // ═══════════════════════════════════
  {
    id: 16, chapter: 4,
    title: '氧化还原初探',
    subtitle: '第四章 · 综合挑战',
    description: '氧化还原反应：氧化剂得到电子，还原剂失去电子。化合价升高被氧化，降低被还原。',
    maxRounds: 12,
    enemyName: '氧化魔法师',
    enemyEmoji: '🔮',
    enemyHP: 180,
    playerHP: 100,
    armorSequence: [
      { armorId: 'O2',    hp: 1, label: '氧化护甲（需还原剂）' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（被还原）' },
      { armorId: 'Cu',    hp: 1, label: '铜护甲（被氯气氧化）' },
      { armorId: 'O2',    hp: 1, label: '氧化护甲（需还原剂）' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（被还原）' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 15, label: '氧化冲击', icon: '🔮' },
      { type: 'corrode',   value: 12, label: '氧化腐蚀（防御-12）', icon: '🧪' },
      { type: 'attack',    value: 15, label: '氧化冲击', icon: '🔮' },
      { type: 'strengthen',value: 12, label: '氧化蓄力', icon: '⚡' },
      { type: 'attack',    value: 27, label: '氧化爆发', icon: '💥' },
      { type: 'attack',    value: 15, label: '氧化冲击', icon: '🔮' },
      { type: 'corrode',   value: 15, label: '强氧化腐蚀（防御-15）', icon: '🧪' },
      { type: 'shield',    value: 30, label: '氧化膜防护', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '氧化冲击', icon: '🔮' },
      { type: 'strengthen',value: 15, label: '超氧化蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '超氧化爆发', icon: '💥' },
      { type: 'attack',    value: 35, label: '终极氧化', icon: '💥' },
    ],
    playerDeck: ['Env_Heat', 'C', 'Env_Ignite', 'H2', 'Env_Aqueous', 'Fe', 'C', 'Cl2', 'H2', 'Env_Heat', 'Ar', 'C', 'Fe', 'H2', 'Cl2', 'C', 'Ar'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['C', 'H2'],
      immuneToCards: ['NaOH', 'HCl'],
      cardDamageMultipliers: { 'C': 1.6, 'H2': 1.5, 'Fe': 1.4, 'Cl2': 1.3 },
      traitDescription: '氧化魔法师由氧化还原反应组成。C和H₂是还原剂，对本关卒伤害最高！对酸碱牌完全免疫。',
    },
    hint: '护甲化学式序列：O₂、Fe₂O₃、Cu、O₂、Fe₂O₃。思考：氧化还原反应中，还原剑是什么？注意：Cl₂点燃可氧化铜（Cu + Cl₂ → CuCl₂）！',
    knowledgeCardId: 'kc-redox',
    objective: '在12回合内击败氧化魔法师',
    difficulty: 'hard',
  },
  {
    id: 17, chapter: 4,
    title: '酸碱盐综合',
    subtitle: '第四章 · 综合挑战',
    description: '酸、碱、盐之间的转化关系：酸+碱→盐+水，盐+酸→新盐+新酸，盐+碱→新盐+新碱。',
    maxRounds: 12,
    enemyName: '盐晶法师',
    enemyEmoji: '💎',
    enemyHP: 190,
    playerHP: 100,
    armorSequence: [
      { armorId: 'CaCO3', hp: 1, label: '碳酸钙护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'HCl',   hp: 1, label: '酸护甲' },
      { armorId: 'CaCO3', hp: 1, label: '碳酸钙护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 15, label: '盐晶冲击', icon: '💎' },
      { type: 'attack',    value: 15, label: '盐晶冲击', icon: '💎' },
      { type: 'corrode',   value: 12, label: '盐酸腐蚀（防御-12）', icon: '🧪' },
      { type: 'strengthen',value: 12, label: '结晶蓄力', icon: '⚡' },
      { type: 'attack',    value: 27, label: '盐晶爆发', icon: '💥' },
      { type: 'shield',    value: 30, label: '盐晶防护', icon: '🛡️' },
      { type: 'attack',    value: 15, label: '盐晶冲击', icon: '💎' },
      { type: 'corrode',   value: 15, label: '强酸腐蚀（防御-15）', icon: '🧪' },
      { type: 'attack',    value: 15, label: '盐晶冲击', icon: '💎' },
      { type: 'strengthen',value: 15, label: '超级蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '盐晶大爆发', icon: '💥' },
      { type: 'attack',    value: 38, label: '终极盐晶', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'HCl', 'NaOH', 'Ca_OH_2', 'H2SO4', 'HCl', 'Env_Aqueous', 'Ar', 'NaOH', 'HCl', 'Ca_OH_2', 'H2SO4', 'NaOH', 'Ar', 'HCl'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['HCl', 'H2SO4', 'NaOH'],
      cardDamageMultipliers: { 'HCl': 1.4, 'H2SO4': 1.5, 'NaOH': 1.4, 'Ca_OH_2': 1.3 },
      postArmorBreakAllowed: ['HCl', 'NaOH', 'Ca_OH_2', 'H2SO4', 'Ar'],
      postArmorBreakHint: '护甲已破！盐晶法师对非酸碱牌免疫。用HCl/NaOH/Ca(OH)₂/H₂SO₄攻击！',
      traitDescription: '盐晶法师由酸碱盐循环组成。H₂SO₄对本关卒伤害最高！酸 + 碱 → 盐 + 水，盐 + 酸 → 新盐 + 新酸',
    },
    hint: '护甲化学式序列：CaCO₃、NaOH、HCl、CaCO₃、Fe₂O₃、NaOH。思考：酸碱盐之间如何转化？哪些牌能破酸护甲？哪些能破碱护甲？',
    knowledgeCardId: 'kc-acid-base-salt',
    objective: '在12回合内击败盐晶法师',
    difficulty: 'hard',
  },
  {
    id: 18, chapter: 4,
    title: '工业化学',
    subtitle: '第四章 · 综合挑战',
    description: '工业上用高炉炼铁（C还原Fe₂O₃），用电解食盐水制备NaOH和Cl₂。掌握工业化学的核心反应！',
    maxRounds: 13,
    enemyName: '工业机械巨人',
    enemyEmoji: '🏭',
    enemyHP: 210,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（高炉还原）' },
      { armorId: 'CO2',   hp: 1, label: 'CO₂护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（电解工业）' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲（电解产物）' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲' },
      { armorId: 'CO2',   hp: 1, label: 'CO₂护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 16, label: '机械冲击', icon: '🏭' },
      { type: 'attack',    value: 16, label: '机械冲击', icon: '🏭' },
      { type: 'corrode',   value: 12, label: '工业腐蚀（防御-12）', icon: '🧪' },
      { type: 'strengthen',value: 14, label: '机械蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '机械爆发', icon: '💥' },
      { type: 'shield',    value: 35, label: '钢铁防护', icon: '🛡️' },
      { type: 'attack',    value: 16, label: '机械冲击', icon: '🏭' },
      { type: 'corrode',   value: 15, label: '强腐蚀（防御-15）', icon: '🧪' },
      { type: 'attack',    value: 16, label: '机械冲击', icon: '🏭' },
      { type: 'strengthen',value: 18, label: '超级蓄力', icon: '⚡' },
      { type: 'attack',    value: 34, label: '超级机械爆发', icon: '💥' },
      { type: 'attack',    value: 16, label: '机械冲击', icon: '🏭' },
      { type: 'attack',    value: 40, label: '终极机械', icon: '💥' },
    ],
    playerDeck: ['Env_Heat', 'C', 'Env_Aqueous', 'Ca_OH_2', 'Fe', 'HCl', 'C', 'NaOH', 'Env_Heat', 'Ar', 'C', 'Ca_OH_2', 'HCl', 'Fe', 'C', 'NaOH', 'Ar'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['C', 'Fe'],
      cardDamageMultipliers: { 'C': 1.6, 'Fe': 1.5, 'Ca_OH_2': 1.4, 'HCl': 1.3, 'NaOH': 1.3 },
      postArmorBreakAllowed: ['C', 'Ca_OH_2', 'Fe', 'HCl', 'NaOH', 'Ar'],
      postArmorBreakHint: '护甲已破！工业机械巨人对非工业反应牌免疫。用C/Fe/Ca(OH)₂/HCl攻击！',
      traitDescription: '工业机械巨人由工业化学组成。C对本关卒伤害最高！高炉炼铁：Fe₂O₃ + 3C → 2Fe + 3CO₂',
    },
    hint: '护甲化学式序列：Fe₂O₃、CO₂、Fe₂O₃、NaOH、Fe₂O₃、CO₂。思考：高炉炼铁用什么还原铁锈？注意：Cl₂是电解食盐水的产物，但此关主要用C还原铁锈和CO₂。',
    knowledgeCardId: 'kc-industry',
    objective: '在13回合内击败工业机械巨人',
    difficulty: 'hard',
  },
  {
    id: 19, chapter: 4,
    title: '元素周期律',
    subtitle: '第四章 · 综合挑战',
    description: '元素周期表中，同族元素性质相似，同周期从左到右金属性递减。综合运用所有知识！',
    maxRounds: 13,
    enemyName: '元素周期表守护者',
    enemyEmoji: '📊',
    enemyHP: 220,
    playerHP: 100,
    armorSequence: [
      { armorId: 'Na',    hp: 1, label: '碱金属护甲' },
      { armorId: 'CO2',   hp: 1, label: '酸性气体护甲' },
      { armorId: 'Al',    hp: 1, label: '两性金属护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '过渡金属护甲' },
      { armorId: 'CaCO3', hp: 1, label: '碳酸盐护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 16, label: '元素冲击', icon: '📊' },
      { type: 'corrode',   value: 12, label: '元素腐蚀（防御-12）', icon: '🧪' },
      { type: 'attack',    value: 16, label: '元素冲击', icon: '📊' },
      { type: 'strengthen',value: 14, label: '周期蓄力', icon: '⚡' },
      { type: 'attack',    value: 30, label: '元素爆发', icon: '💥' },
      { type: 'shield',    value: 35, label: '元素防护', icon: '🛡️' },
      { type: 'corrode',   value: 15, label: '强元素腐蚀（防御-15）', icon: '🧪' },
      { type: 'attack',    value: 16, label: '元素冲击', icon: '📊' },
      { type: 'strengthen',value: 18, label: '超级蓄力', icon: '⚡' },
      { type: 'attack',    value: 34, label: '超级元素爆发', icon: '💥' },
      { type: 'attack',    value: 16, label: '元素冲击', icon: '📊' },
      { type: 'attack',    value: 16, label: '元素冲击', icon: '📊' },
      { type: 'attack',    value: 42, label: '终极元素律', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Env_Heat', 'Fe', 'NaOH', 'HCl', 'C', 'Env_Aqueous', 'Ar', 'MnO2', 'H2O', 'Fe', 'HCl', 'NaOH', 'C', 'Ar', 'MnO2'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['H2O', 'Fe', 'HCl', 'C'],
      cardDamageMultipliers: { 'H2O': 1.4, 'Fe': 1.4, 'HCl': 1.5, 'C': 1.5, 'NaOH': 1.3, 'MnO2': 1.0 },
      postArmorBreakAllowed: ['H2O', 'Fe', 'NaOH', 'HCl', 'C', 'Ar', 'MnO2'],
      postArmorBreakHint: '护甲已破！元素周期表守护者对非化学反应牌免疫。用化学反应牌攻击！',
      traitDescription: '元素周期表守护者涉及所有元素类型。HCl和C对本关卒伤害最高！元素周期律：同族元素性质相似，同周期金属性递减。',
    },
    hint: '护甲化学式序列：Na、CO₂、Al、Fe₂O₃、CaCO₃、NaOH。思考：元素周期律如何帮助你预判元素性质？注意：CO₂是酸性气体，NaOH能吸收CO₂（2NaOH + CO₂ → Na₂CO₃ + H₂O）。',
    knowledgeCardId: 'kc-periodic',
    objective: '在13回合内击败元素周期表守护者',
    difficulty: 'hard',
  },
  {
    id: 20, chapter: 4,
    title: '最终决战',
    subtitle: '第四章 · 终极Boss',
    description: '元素之神降临！掌握所有化学知识，运用催化剂、护盾和指示剂，完成最终挑战！',
    maxRounds: 15,
    enemyName: '元素之神',
    enemyEmoji: '⚡',
    enemyHP: 280,
    playerHP: 120,
    armorSequence: [
      { armorId: 'Na',    hp: 1, label: '碱金属护甲' },
      { armorId: 'O2',    hp: 1, label: '氧化护甲' },
      { armorId: 'Fe',    hp: 1, label: '过渡金属护甲' },
      { armorId: 'NaOH',  hp: 1, label: '碱护甲' },
      { armorId: 'CaCO3', hp: 1, label: '碳酸盐护甲' },
      { armorId: 'CO2',   hp: 1, label: '酸性气体护甲' },
      { armorId: 'Al',    hp: 1, label: '两性护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 18, label: '神力冲击', icon: '⚡' },
      { type: 'corrode',   value: 15, label: '元素腐蚀（防御-15）', icon: '🧪' },
      { type: 'attack',    value: 18, label: '神力冲击', icon: '⚡' },
      { type: 'strengthen',value: 15, label: '神力蓄力', icon: '⚡' },
      { type: 'attack',    value: 33, label: '神力爆发', icon: '💥' },
      { type: 'shield',    value: 40, label: '元素神盾', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '神力冲击', icon: '⚡' },
      { type: 'corrode',   value: 18, label: '强元素腐蚀（防御-18）', icon: '🧪' },
      { type: 'strengthen',value: 20, label: '超神蓄力', icon: '⚡' },
      { type: 'attack',    value: 38, label: '超神爆发', icon: '💥' },
      { type: 'attack',    value: 18, label: '神力冲击', icon: '⚡' },
      { type: 'shield',    value: 45, label: '终极神盾', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '神力冲击', icon: '⚡' },
      { type: 'strengthen',value: 25, label: '终极蓄力', icon: '⚡' },
      { type: 'attack',    value: 50, label: '终极元素爆发', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Env_Heat', 'C', 'Env_Ignite', 'O2', 'Zn', 'HCl', 'NaOH', 'MnO2', 'Env_Aqueous', 'Ar', 'H2O', 'C', 'Fe', 'HCl', 'NaOH', 'Litmus', 'Ar', 'MnO2'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['H2O', 'C', 'HCl', 'NaOH'],
      cardDamageMultipliers: { 'H2O': 1.5, 'C': 1.5, 'HCl': 1.5, 'NaOH': 1.5, 'Fe': 1.4, 'Zn': 1.4, 'MnO2': 1.0 },
      postArmorBreakAllowed: ['H2O', 'C', 'Zn', 'HCl', 'NaOH', 'Fe', 'Ar', 'MnO2', 'Litmus'],
      postArmorBreakHint: '护甲已破！元素之神对非化学反应牌免疫。用化学反应牌攻击！',
      traitDescription: '元素之神掉有所有化学知识！所有化学反应牌对本关卒伤害均加强。充分利用MnO₂催化剂和Ar护盾，提前规划每一张牌！',
      // 氧化还原护甲机制：护甲分氧化态和还原态，用错会给Boss回血
      // 化学原理：氧化剂只能破还原态护甲，还原剂只能破氧化态护甲
      redoxArmor: true,
      initialRedoxState: 'oxidized',
      oxidizedBreakers: ['C', 'H2', 'Fe', 'Zn'],    // 还原剂：能破氧化态护甲
      reducedBreakers: ['O2', 'Cl2', 'MnO2'],        // 氧化剂：能破还原态护甲
      redoxWrongPenalty: 15,
      redoxHint: '氧化还原护甲！氧化态护甲需要还原剂（C/H₂/Fe/Zn）破除，还原态护甲需要氧化剂（O₂/Cl₂）破除。用错将给元素之神回血 15点！',
    },
    hint: '护甲化学式序列：Na、O₂、Fe、NaOH、CaCO₃、CO₂、Al。思考：如何利用催化剑连续出牌？石蕤试液能帮你判断护甲类型。注意：CO₂护甲用NaOH或Ca(OH)₂破除。每一张牌都很宝贵！',
    knowledgeCardId: 'kc-final',
    objective: '在15回合内击败元素之神',
    difficulty: 'hard',
  },

  // ═══════════════════════════════════
  // 第四章精英小怪（关卡24 · 终极挑战）
  // ═══════════════════════════════════
  {
    id: 24, chapter: 4,
    title: '元素终极考验',
    subtitle: '第四章 · 终极精英',
    description: '元素终极考验降临！这个精英小怪综合了全部四章的化学知识，拥有氧化还原护甲机制和超强攻击能力！这是真正的终极考验！',
    maxRounds: 15,
    enemyName: '终极元素精英',
    enemyEmoji: '🔮',
    enemyHP: 260,
    playerHP: 110,
    armorSequence: [
      { armorId: 'Na',    hp: 1, label: '碱金属护甲' },
      { armorId: 'Fe2O3', hp: 1, label: '铁锈护甲（被还原）' },
      { armorId: 'Al',    hp: 1, label: '两性护甲' },
      { armorId: 'CaCO3', hp: 1, label: '碳酸盐护甲' },
      { armorId: 'NaOH',  hp: 1, label: '强碱护甲' },
      { armorId: 'CO2',   hp: 1, label: '酸性气体护甲' },
      { armorId: 'Fe',    hp: 1, label: '过渡金属护甲' },
    ],
    armorChangeInterval: 2,
    enemyActions: [
      { type: 'attack',    value: 18, label: '终极冲击', icon: '🔮' },
      { type: 'corrode',   value: 15, label: '终极腐蚀（防御-15）', icon: '🧪' },
      { type: 'attack',    value: 18, label: '终极冲击', icon: '🔮' },
      { type: 'strengthen',value: 15, label: '终极蓄力', icon: '⚡' },
      { type: 'attack',    value: 33, label: '终极爆发', icon: '💥' },
      { type: 'shield',    value: 40, label: '终极元素盾', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '终极冲击', icon: '🔮' },
      { type: 'corrode',   value: 18, label: '超级腐蚀（防御-18）', icon: '🧪' },
      { type: 'strengthen',value: 20, label: '超神蓄力', icon: '⚡' },
      { type: 'attack',    value: 38, label: '超神爆发', icon: '💥' },
      { type: 'attack',    value: 18, label: '终极冲击', icon: '🔮' },
      { type: 'shield',    value: 45, label: '终极神盾', icon: '🛡️' },
      { type: 'attack',    value: 18, label: '终极冲击', icon: '🔮' },
      { type: 'strengthen',value: 25, label: '终极神力蓄力', icon: '⚡' },
      { type: 'attack',    value: 55, label: '终极元素爆发', icon: '💥' },
    ],
    playerDeck: ['Env_Aqueous', 'H2O', 'Env_Heat', 'C', 'Env_Ignite', 'O2', 'Zn', 'HCl', 'NaOH', 'MnO2', 'Env_Aqueous', 'Ar', 'H2O', 'C', 'Fe', 'HCl', 'NaOH', 'Litmus', 'Ar', 'MnO2', 'H2O'],
    initialHandSize: 5,
    maxPlaysPerTurn: 3,
    bossTraits: {
      weakToCards: ['H2O', 'C', 'HCl', 'NaOH'],
      cardDamageMultipliers: { 'H2O': 1.5, 'C': 1.5, 'HCl': 1.5, 'NaOH': 1.5, 'Fe': 1.4, 'Zn': 1.4, 'MnO2': 1.0 },
      postArmorBreakAllowed: ['H2O', 'C', 'Zn', 'HCl', 'NaOH', 'Fe', 'Ar', 'MnO2', 'Litmus'],
      postArmorBreakHint: '护甲已破！终极元素精英对非化学反应牌免疫。用化学反应牌攻击！',
      traitDescription: '终极元素精英拥有全部化学知识！所有化学反应牌对本关卡伤害均加强。充分利用MnO₂催化剑和Ar护盾，提前规划每一张牌！',
      sodiumExplosion: true,
      sodiumExplosionDamage: 12,
      sodiumExplosionHint: '钓爆！终极元素精英的钓爆更强烈！溅射伤害 12点！',
      redoxArmor: true,
      initialRedoxState: 'oxidized',
      oxidizedBreakers: ['C', 'H2', 'Fe', 'Zn'],
      reducedBreakers: ['O2', 'Cl2', 'MnO2'],
      redoxWrongPenalty: 20,
      redoxHint: '氧化还原护甲激活！氧化态护甲需要还原剑（C/H₂/Fe/Zn）破除，还原态护甲需要氧化剑（O₂/Cl₂）破除。用错将给终极元素精英回血 20点！',
    },
    hint: '护甲序列：Na、Fe₂O₃、Al、CaCO₃、NaOH、CO₂、Fe。综合运用全部四章知识！小心氧化还原护甲和钓爆机制！',
    knowledgeCardId: 'kc-final',
    objective: '在15回合内击败终极元素精英',
    difficulty: 'hard',
  },
];

// 知识卡片数据
export interface KnowledgeCard {
  id: string;
  title: string;
  element?: string;
  content: string;
  equation?: string;
  funFact: string;
  category: string;
}

export const KNOWLEDGE_CARDS: KnowledgeCard[] = [
  {
    id: 'kc-H2', title: '氢气 H₂', element: 'H',
    content: '氢气是最轻的气体，也是宇宙中含量最多的元素。氢气在空气中燃烧生成水，是清洁能源的重要候选。',
    equation: '2H₂ + O₂ →(点燃) 2H₂O',
    funFact: '太阳的能量来自氢核聚变！每秒有6亿吨氢转化为氦。',
    category: '非金属',
  },
  {
    id: 'kc-Na', title: '钠 Na', element: 'Na',
    content: '钠是银白色软金属，化学性质极活泼。钠遇水剧烈反应，生成氢氧化钠和氢气。钠的焰色反应为黄色。',
    equation: '2Na + 2H₂O → 2NaOH + H₂↑',
    funFact: '食盐（NaCl）就是钠的化合物！人体每天需要约2克钠来维持生命活动。',
    category: '碱金属',
  },
  {
    id: 'kc-K', title: '钾 K', element: 'K',
    content: '钾比钠更活泼，遇水反应更剧烈，甚至会引起燃烧和爆炸。钾的焰色反应为紫色。',
    equation: '2K + 2H₂O → 2KOH + H₂↑ (剧烈)',
    funFact: '香蕉富含钾元素！成年人每天需要约2000毫克钾来维持心脏健康。',
    category: '碱金属',
  },
  {
    id: 'kc-Li', title: '锂 Li', element: 'Li',
    content: '锂是最轻的金属，密度比水还小。锂电池是现代电子设备的核心，手机、电动车都用到锂电池。',
    equation: '2Li + 2H₂O → 2LiOH + H₂↑',
    funFact: '你手机里的电池就含有锂！一块手机电池约含3-5克锂。',
    category: '碱金属',
  },
  {
    id: 'kc-Cl', title: '氯 Cl₂', element: 'Cl',
    content: '氯气是黄绿色有毒气体，具有强氧化性。氯气可以杀菌消毒，自来水就用氯气消毒。',
    equation: '2Fe + 3Cl₂ →(点燃) 2FeCl₃',
    funFact: '游泳池的消毒气味来自氯！但实际上是氯气与有机物反应产生的氯胺，而非纯氯气。',
    category: '卤素',
  },
  {
    id: 'kc-Fe', title: '铁 Fe', element: 'Fe',
    content: '铁是地球上含量最多的金属元素。铁在潮湿空气中会生锈（Fe₂O₃），活动性比铜强，可以置换铜。',
    equation: 'Fe + CuSO₄ → FeSO₄ + Cu',
    funFact: '地球的核心主要由铁和镍组成！地核的温度高达5000℃，铁在那里是液态的。',
    category: '过渡金属',
  },
  {
    id: 'kc-C', title: '碳 C', element: 'C',
    content: '碳是生命的基础元素。碳有多种同素异形体：金刚石（最硬）、石墨（最软导体）、C₆₀（足球烯）。',
    equation: 'C + O₂ →(点燃) CO₂ | 2C + O₂(不足) →(点燃) 2CO',
    funFact: '钻石和铅笔芯都是碳！金刚石和石墨都由纯碳组成，但结构不同导致性质天壤之别。',
    category: '非金属',
  },
  {
    id: 'kc-NaOH', title: '氢氧化钠 NaOH', element: 'NaOH',
    content: 'NaOH俗称"烧碱"或"火碱"，是强碱。能与酸发生中和反应，能溶解铝，能吸收CO₂。',
    equation: 'NaOH + HCl → NaCl + H₂O',
    funFact: '肥皂就是用NaOH制造的！油脂与NaOH反应（皂化反应）生成甘油和脂肪酸钠（肥皂）。',
    category: '化合物',
  },
  {
    id: 'kc-HCl', title: '盐酸 HCl', element: 'HCl',
    content: '盐酸是氯化氢（HCl）的水溶液，是强酸。能与碱中和，能溶解碳酸盐、铁锈等。',
    equation: 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑',
    funFact: '你的胃里就有盐酸！胃酸的主要成分是盐酸，pH约为1.5-2，帮助消化食物。',
    category: '化合物',
  },
  {
    id: 'kc-H2O', title: '水 H₂O', element: 'H₂O',
    content: '水是最重要的溶剂，能与活泼金属（Na、K）反应，能溶解多种离子化合物。',
    equation: '2Na + 2H₂O → 2NaOH + H₂↑',
    funFact: '水是唯一在自然界中以固、液、气三态存在的物质！冰的密度比液态水小，所以冰会浮在水面上。',
    category: '化合物',
  },
  {
    id: 'kc-NaCl', title: '食盐 NaCl', element: 'NaCl',
    content: 'NaCl是最常见的盐，由钠和氯组成。食盐是人类最早使用的调味品，也是重要的工业原料。',
    equation: '2Na + Cl₂ → 2NaCl',
    funFact: '古罗马士兵的薪水有时用盐支付！英语"salary"（薪水）就来自拉丁语"sal"（盐）。',
    category: '化合物',
  },
  {
    id: 'kc-MnO2', title: '二氧化锰 MnO₂', element: 'MnO₂',
    content: 'MnO₂是H₂O₂分解的催化剂，可以加快反应速率但不被消耗。催化剂是化学工业的重要工具。',
    equation: '2H₂O₂ →(MnO₂) 2H₂O + O₂↑',
    funFact: '催化剂就像化学反应的"媒人"——它让反应更快发生，但自己不参与反应，反应后还能继续使用！',
    category: '特殊',
  },
  {
    id: 'kc-H2SO4', title: '硫酸 H₂SO₄', element: 'H₂SO₄',
    content: '硫酸是工业上最重要的酸，产量最大。浓硫酸有强腐蚀性、吸水性和脱水性。',
    equation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O',
    funFact: '硫酸是化工之母！全球每年生产约2亿吨硫酸，用于制造化肥、炸药、染料等。',
    category: '化合物',
  },
  {
    id: 'kc-Al', title: '铝 Al', element: 'Al',
    content: '铝是地壳中含量最多的金属元素。铝是两性金属，既能与酸反应，也能与碱反应。',
    equation: '2Al + 2NaOH + 2H₂O → 2NaAlO₂ + 3H₂↑',
    funFact: '铝曾经比黄金还贵！19世纪初，铝的提炼技术很难，拿破仑三世只在宴会上给贵宾用铝制餐具。',
    category: '过渡金属',
  },
  {
    id: 'kc-CaCO3', title: '碳酸钙 CaCO₃', element: 'CaCO₃',
    content: '碳酸钙是石灰石、大理石、贝壳的主要成分。遇酸分解，高温分解生成CaO和CO₂。',
    equation: 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑',
    funFact: '长城的砖缝用石灰（CaO）砌成！CaO遇水生成Ca(OH)₂，Ca(OH)₂与空气中CO₂反应重新生成CaCO₃，越来越坚固。',
    category: '化合物',
  },
  {
    id: 'kc-activity', title: '金属活动性顺序', element: '',
    content: '金属活动性顺序（从强到弱）：K > Ca > Na > Mg > Al > Zn > Fe > Ni > Sn > Pb > H > Cu > Hg > Ag > Pt > Au。活动性强的金属能置换活动性弱的金属。',
    equation: 'Fe + CuSO₄ → FeSO₄ + Cu（Fe活动性 > Cu）',
    funFact: '黄金（Au）排在最后，这就是为什么黄金不会生锈，在地球上能以单质形式存在数千年！',
    category: '规律',
  },
  {
    id: 'kc-displacement', title: '置换反应', element: '',
    content: '置换反应：A + BC → AC + B。活动性强的金属能从盐溶液中置换出活动性弱的金属。',
    equation: 'Zn + FeSO₄ → ZnSO₄ + Fe（Zn活动性 > Fe）',
    funFact: '古代炼铜就用了置换反应！把铁放入硫酸铜溶液，铁会慢慢变成铜色，这就是"湿法炼铜"。',
    category: '反应类型',
  },
  {
    id: 'kc-redox', title: '氧化还原反应', element: '',
    content: '氧化还原反应：有电子转移的反应。氧化剂得到电子（化合价降低，被还原），还原剂失去电子（化合价升高，被氧化）。',
    equation: 'Fe₂O₃ + 3CO →(高温) 2Fe + 3CO₂（CO是还原剂）',
    funFact: '呼吸作用就是氧化还原反应！葡萄糖被氧化，氧气被还原，释放出维持生命的能量。',
    category: '反应类型',
  },
  {
    id: 'kc-acid-base-salt', title: '酸碱盐关系', element: '',
    content: '酸、碱、盐之间可以相互转化：酸+碱→盐+水（中和），盐+酸→新盐+新酸，盐+碱→新盐+新碱。',
    equation: 'NaOH + HCl → NaCl + H₂O（中和反应）',
    funFact: '人体的血液pH维持在7.35-7.45之间！酸碱平衡对生命至关重要，偏离这个范围会危及生命。',
    category: '规律',
  },
  {
    id: 'kc-industry', title: '工业化学', element: '',
    content: '高炉炼铁：用焦炭（C）在高温下还原铁矿石（Fe₂O₃）。工业制盐酸：H₂和Cl₂直接化合。工业合成氨：N₂和H₂在高温高压催化剂下反应。',
    equation: 'Fe₂O₃ + 3CO →(高温) 2Fe + 3CO₂',
    funFact: '一座现代高炉每天能炼出5000吨铁！高炉内温度高达1500℃，相当于太阳表面温度的1/4。',
    category: '应用',
  },
  {
    id: 'kc-periodic', title: '元素周期律', element: '',
    content: '元素周期律：元素的性质随原子序数的增加呈现周期性变化。同族元素性质相似，同周期从左到右金属性减弱、非金属性增强。',
    equation: '第一周期：H, He | 第二周期：Li, Be, B, C, N, O, F, Ne',
    funFact: '门捷列夫预言了当时未知元素的存在！他在1869年制作元素周期表时，留下了空格，后来这些元素（如镓、锗、钪）都被发现了。',
    category: '规律',
  },
  {
    id: 'kc-final', title: '化学的奥秘', element: '',
    content: '恭喜你掌握了初中化学的核心知识！化学是研究物质组成、结构、性质和变化规律的科学，是连接宏观世界和微观世界的桥梁。',
    equation: '物质 → 元素 → 原子 → 电子 → 量子',
    funFact: '你的身体是一个化学工厂！每秒钟体内发生约37万亿次化学反应，维持着你的生命活动。',
    category: '综合',
  },
  {
    id: 'kc-Ar', title: '氩气 Ar', element: 'Ar',
    content: '氩气是地球大气中含量最多的稀有气体（约0.93%）。化学性质极不活泼，不与任何物质反应。',
    equation: '（无反应方程式，Ar不参与化学反应）',
    funFact: '白炽灯泡里充的就是氩气！氩气防止灯丝在高温下被氧化，延长灯泡寿命。',
    category: '稀有气体',
  },
  {
    id: 'kc-He', title: '氦气 He', element: 'He',
    content: '氦气是最轻的稀有气体，化学性质完全惰性。氦气比空气轻，常用于气球和飞艇。',
    equation: '（无反应方程式，He不参与化学反应）',
    funFact: '氦气是地球上最稀缺的元素之一！氦气会逃逸到太空，地球上的氦气主要来自放射性元素的衰变。',
    category: '稀有气体',
  },
  {
    id: 'kc-CaOH2', title: '氢氧化钙 Ca(OH)₂', element: 'Ca(OH)₂',
    content: '氢氧化钙俗称"熟石灰"或"消石灰"，是弱碱。能与酸中和，能吸收CO₂，用于建筑和农业。',
    equation: 'Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O',
    funFact: '石灰水变浑浊是检验CO₂的经典方法！Ca(OH)₂与CO₂反应生成白色CaCO₃沉淀，使溶液变浑浊。',
    category: '化合物',
  },
  {
    id: 'kc-O2', title: '氧气 O₂', element: 'O₂',
    content: '氧气是地球大气的重要组成部分（约21%）。氧气支持燃烧，是大多数生物呼吸的必需物质。',
    equation: '3Fe + 2O₂ →(点燃) Fe₃O₄（铁在纯氧中燃烧）',
    funFact: '铁在纯氧中燃烧会产生耀眼的火花！这就是为什么焊接时会有火花四溅——铁被氧化的反应。',
    category: '非金属',
  },
  {
    id: 'kc-Zn', title: '锌 Zn', element: 'Zn',
    content: '锌是活动性较强的金属，能与酸反应，能置换铜和铁。锌用于镀锌钢铁防锈，也是人体必需微量元素。',
    equation: 'Zn + H₂SO₄ → ZnSO₄ + H₂↑',
    funFact: '干电池里有锌！普通干电池的负极就是锌，正极是二氧化锰，电解质是氯化铵。',
    category: '过渡金属',
  },
  {
    id: 'kc-CuSO4', title: '硫酸铜 CuSO₄', element: 'CuSO₄',
    content: '硫酸铜是蓝色晶体，是典型的铜盐。铁和锌可以从硫酸铜溶液中置换出铜。',
    equation: 'Fe + CuSO₄ → FeSO₄ + Cu',
    funFact: '波尔多液（硫酸铜+石灰水）是经典农药！19世纪法国农民发现它能防治葡萄病害，沿用至今。',
    category: '化合物',
  },
  {
    id: 'kc-Litmus', title: '酸碱指示剂', element: '',
    content: '石蕊试液遇酸变红，遇碱变蓝，中性为紫色。酚酞遇碱变红，遇酸无色。指示剂帮助判断溶液酸碱性。',
    equation: 'pH < 7（酸性）| pH = 7（中性）| pH > 7（碱性）',
    funFact: '石蕊来自地衣植物！古代人发现某些地衣的提取物遇酸变色，这就是最早的酸碱指示剂。',
    category: '特殊',
  },
  {
    id: 'kc-metals', title: '金属的性质', element: '',
    content: '金属的共同性质：导电、导热、有金属光泽、有延展性。金属活动性决定其化学反应能力。',
    equation: '金属活动性：K>Ca>Na>Mg>Al>Zn>Fe>Cu>Hg>Ag>Pt>Au',
    funFact: '金属铯在室温下是液态的！铯的熔点只有28.5℃，比人体体温还低，在手心里就会融化。',
    category: '规律',
  },
  {
    id: 'kc-CO2', title: '二氧化碳 CO₂', element: 'CO₂',
    content: 'CO₂是碳完全燃烧的产物，也是光合作用的原料。CO₂能与碱（如NaOH、Ca(OH)₂）反应，是酸性氧化物。',
    equation: 'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',
    funFact: '植物用CO₂制造食物！光合作用每年固定约1200亿吨CO₂，是地球碳循环的关键。',
    category: '非金属',
  },
  {
    id: 'kc-Fe2O3', title: '氧化铁 Fe₂O₃', element: 'Fe₂O₃',
    content: '氧化铁是铁锈的主要成分，红棕色固体。可被酸溶解，也可被碳、氢气等还原剂还原为铁。',
    equation: 'Fe₂O₃ + 3CO →(高温) 2Fe + 3CO₂',
    funFact: '火星是红色的就因为Fe₂O₃！火星表面覆盖着大量氧化铁，这就是它被称为"红色星球"的原因。',
    category: '化合物',
  },
  {
    id: 'kc-Cu', title: '铜 Cu', element: 'Cu',
    content: '铜是人类最早使用的金属之一，活动性较弱，不与稀盐酸反应，但能被活泼金属置换出来。',
    equation: 'Fe + CuSO₄ → FeSO₄ + Cu（铁置换铜）',
    funFact: '人类使用铜已有1万年历史！青铜（铜锡合金）的发明开启了"青铜时代"，推动了人类文明进步。',
    category: '过渡金属',
  },
];

export const KNOWLEDGE_MAP: Record<string, KnowledgeCard> = {};
KNOWLEDGE_CARDS.forEach(k => { KNOWLEDGE_MAP[k.id] = k; });
